apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-vitals-exporter
  namespace: monitor
  labels:
    app: web-vitals-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-vitals-exporter
  template:
    metadata:
      labels:
        app: web-vitals-exporter
      annotations:
        branch: web-vitals-exporter
    spec:
      containers:
        - name: log-server
          image: 'gcr.io/staging-omnimerse/web-vitals-exporter:v1.2' # {"$imagepolicy": "flux-system:develop-web-vitals-exporter"}
          ports:
            - name: standard
              containerPort: 2113
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 16Mi
            requests:
              cpu: 10m
              memory: 16Mi
          imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 3
---
apiVersion: v1
kind: Service
metadata:
  name: web-vitals-exporter
  namespace: monitor
spec:
  ports:
    - name: http
      protocol: TCP
      port: 2113
      targetPort: 2113
  selector:
    app: web-vitals-exporter
  type: ClusterIP
